### ISSUE TITLE
Unnecessary Code

### ISSUE THREAD

**Issue by pabloCabrera7** [midudev/react-live-coding#15]
Hola Miguel, estuve viendo y analizando el código, creo que esta llamada al hook de useGif ( y la siguiente linea de codigo) es innecesaria ya que al invocar a este hook, estamos realizando una nueva llamada a la API de gif que podríamos evitar, y que además muy probablemente el detalle del gif que queremos puede que no esté entre estos gif. Y asi también nos ahorramos la siguiente linea donde buscamos el gif.
Sería mejor simplemente realizar una llamada a la api con la id del gif del cual queremos saber el detalle, no ? O usar el useContext para obtener los gifs que ya tenemos sin hacer una nueva llamada a la API. ?
Espero haberme explicado. 
Gracias y saludos.
@midudev 
https://github.com/midudev/react-live-coding/blob/990ab8c88339c0da90242b7add415caaf0d1af3f/src/hooks/useSingleGif.js#L6

**Comment by midudev** [comment]
¡Me lo miraré! Gracias por comentarlo Pablo! 🙇
