### ISSUE TITLE
Desabilitar la extension Deno en este proyecto

### ISSUE THREAD

**Issue by azacchino** [midudev/react-live-coding#20]
Vi que en el ultimo video la extensión de Deno se entrometia en el react. Para evitar eso lo podes deshabilitar (solo para este proyecto) la extensión, poniendo en el el archivo /.vscode/settings.json y en el pones:  ` { "deno.enable": false}`

/
|-> .vscode
__|-> settings.json

**Comment by midudev** [comment]
¡Gracias Andrés! Ahora lo añado. :)

**Comment by midudev** [comment]
Fixed: https://github.com/midudev/react-live-coding/commit/48132f48dfcd145dfd8a2bc912c0ddbb2aef16d5
